CREATE TABLE `user` (
	`ID`		INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
	`token`		TEXT NOT NULL UNIQUE,
	`config`	TEXT
);

CREATE TABLE `chat` ( 
	`ID` INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT, 
	`token` TEXT NOT NULL UNIQUE, 
	`name` TEXT, 
	`protected` INTEGER NOT NULL DEFAULT 0, 
	`chat_key` TEXT 
);